base_url: /
simple_copy:
  - FeFeHydrogenase.html
  - media/*
  - stuff/*
media_root: media # Relative path from content folder.
media_url: /media # URL where the media files are served from.
server:
  extensions:
    default: text/html

plugins:
  - hyde.ext.plugins.meta.MetaPlugin
  - hyde.ext.plugins.meta.AutoExtendPlugin
  - hyde.ext.plugins.text.SyntextPlugin
  - hyde.ext.plugins.text.TextlinksPlugin
  - hyde.ext.plugins.urls.UrlCleanerPlugin
  - hyde.ext.plugins.meta.SorterPlugin
  - hyde.ext.plugins.meta.TaggerPlugin
  - hyde.ext.plugins.structure.PaginatorPlugin

syntax:
  use_figure: False

sorter:
  name:
    attr: name
    filters:
      # source_file.kind: html
      is_processable: True
  time:
     attr: meta.created
     reverse: True
     filters:
       # source_file.kind: html
       is_processable: True

tagger:
  sorter: time
  archives:
    atom:
      source: blog
      target: blog/tags
      template: tag.xml.j2
      extension: xml
    blog:
      source: blog
      target: blog/tags
      template: tag.j2

urlcleaner:
  index_file_names:
    - index.html
  strip_extensions:
    - html

context:
    data:
        site_url: http://act-epr.org
        site_title: Act-EPR MSC Fellowship 
        blog_title: Act-EPR
        author:
            name: Jason W. Sidabras 
            url: "http://act-epr.org"
        google_analytics_id: UA-91383149-1 
